# Automatically generated by /Users/TyounanMOTI/bin/cmake-flymake-generate, you may remove it using `cmake-flymake-remove' as you please
.PHONY: check-syntax
check-syntax:
	${CXX} -fsyntax-only ${CXX_FLAGS} ${CXX_DEFINES} -S ${CHK_SOURCES}
